### ISSUE TITLE
Support SCS 3.0

### ISSUE THREAD

**Issue by bodono** [ankane/scs-ruby#2]
The SCS 3.0 PR is here: https://github.com/cvxgrp/scs/pull/169

The new version of SCS is overall much faster and more reliable, as well as supporting quadratics natively (and other new features).

**Comment by ankane** [comment]
Awesome, thanks @bodono! Added support in the [edge](https://github.com/ankane/scs/compare/edge) branch and will merge once 3.0 is released.

**Comment by bodono** [comment]
Wow, that was fast, great work! If you have any spare cycles it would be great to have your input on the website, in particular the Ruby API and an example or two if you have time. The website would name you as the maintainer of the API of course.

Current API page here (missing Ruby): https://www.cvxgrp.org/scs/api/index.html#interfaces

Here is the website source: https://github.com/cvxgrp/scs/tree/3.0.0/docs/src

**Comment by ankane** [comment]
Started it [here](https://github.com/cvxgrp/scs/compare/3.0.0...ankane:ruby-docs). Will wait for the other API docs and examples to see if it's easy to match.

**Comment by bodono** [comment]
Great, thanks.

**Comment by bodono** [comment]
The PR updating SCS to 3.0 has landed now, so feel free to land your changes too!

**Comment by ankane** [comment]
Hey @bodono, congrats on the release! I pushed a new release for 3.0 yesterday and will try to add Ruby to the docs at some point.

**Comment by bodono** [comment]
Oh awesome, thanks!
